name: Epic
description: "Create an Epic"
labels: "epic :notebook:"
body:
  - type: textarea
    id: abstract
    attributes:
      label: "Abstract:"
      placeholder: |
        (What?) This standard defines the process of cooking a cookie.

  - type: textarea
    id: prerequisites
    attributes:
      label: "Prerequisites:"
      placeholder: Needs cookies to be cooked in advance.

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation:"
      placeholder: |
        (Why?) The cookies are needed to make a cake and users love cookies.

  - type: textarea
    id: references
    attributes:
      label: "References:"
      placeholder: Cooking a cookie, quick recipe...
    validations:
      required: false