export { default as external } from './external.svg'
export { default as logo } from './logo.svg'
export { default as plate } from './plate.svg'
export { default as plateXs } from './plate-xs.svg'
export { default as menuOpen } from './menu-open.svg'
export { default as menuClose } from './menu-close.svg'
